// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type BlogUser struct {
	ID int64 `json:"id"`
	// can be change
	Username string `json:"username"`
	// can be change
	Email    string `json:"email"`
	FullName string `json:"full_name"`
	// male, female, other
	Gender          string `json:"gender"`
	CurrentLocation string `json:"current_location"`
	// password hashed with SHA-512
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	LoginedAt    time.Time `json:"logined_at"`
}

type Post struct {
	ID         int64     `json:"id"`
	SemanticID string    `json:"semantic_id"`
	AuthorID   int64     `json:"author_id"`
	Title      string    `json:"title"`
	Abstract   string    `json:"abstract"`
	Content    string    `json:"content"`
	Tags       []string  `json:"tags"`
	IsArchived bool      `json:"is_archived"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}
