// Code generated by sqlc. DO NOT EDIT.
// source: post.sql

package db

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const createPost = `-- name: CreatePost :one
INSERT INTO post (
  semantic_id,
  author_id,
  title,
  abstract,
  content,
  tags,
  is_archived,
  updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, semantic_id, author_id, title, abstract, content, tags, is_archived, created_at, updated_at
`

type CreatePostParams struct {
	SemanticID string    `json:"semantic_id"`
	AuthorID   int64     `json:"author_id"`
	Title      string    `json:"title"`
	Abstract   string    `json:"abstract"`
	Content    string    `json:"content"`
	Tags       []string  `json:"tags"`
	IsArchived bool      `json:"is_archived"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.SemanticID,
		arg.AuthorID,
		arg.Title,
		arg.Abstract,
		arg.Content,
		pq.Array(arg.Tags),
		arg.IsArchived,
		arg.UpdatedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.SemanticID,
		&i.AuthorID,
		&i.Title,
		&i.Abstract,
		&i.Content,
		pq.Array(&i.Tags),
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM post
WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePost, id)
	return err
}

const getAllPostFromAuthor = `-- name: GetAllPostFromAuthor :many
SELECT id, semantic_id, author_id, title, abstract, content, tags, is_archived, created_at, updated_at FROM post
WHERE author_id = $1
ORDER BY created_at
`

func (q *Queries) GetAllPostFromAuthor(ctx context.Context, authorID int64) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getAllPostFromAuthor, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.SemanticID,
			&i.AuthorID,
			&i.Title,
			&i.Abstract,
			&i.Content,
			pq.Array(&i.Tags),
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostByPostID = `-- name: GetPostByPostID :one
SELECT id, semantic_id, author_id, title, abstract, content, tags, is_archived, created_at, updated_at FROM post
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPostByPostID(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostByPostID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.SemanticID,
		&i.AuthorID,
		&i.Title,
		&i.Abstract,
		&i.Content,
		pq.Array(&i.Tags),
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostBySemanticID = `-- name: GetPostBySemanticID :one
SELECT id, semantic_id, author_id, title, abstract, content, tags, is_archived, created_at, updated_at FROM post
WHERE author_id = $1
AND semantic_id = $2
LIMIT 1
`

type GetPostBySemanticIDParams struct {
	AuthorID   int64  `json:"author_id"`
	SemanticID string `json:"semantic_id"`
}

func (q *Queries) GetPostBySemanticID(ctx context.Context, arg GetPostBySemanticIDParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostBySemanticID, arg.AuthorID, arg.SemanticID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.SemanticID,
		&i.AuthorID,
		&i.Title,
		&i.Abstract,
		&i.Content,
		pq.Array(&i.Tags),
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePost = `-- name: UpdatePost :one
UPDATE post
SET (
  semantic_id,
  author_id,
  title,
  abstract,
  content,
  tags,
  is_archived,
  updated_at
) = (
  $2, $3, $4, $5, $6, $7, $8, $9
)
WHERE id = $1
RETURNING id, semantic_id, author_id, title, abstract, content, tags, is_archived, created_at, updated_at
`

type UpdatePostParams struct {
	ID         int64     `json:"id"`
	SemanticID string    `json:"semantic_id"`
	AuthorID   int64     `json:"author_id"`
	Title      string    `json:"title"`
	Abstract   string    `json:"abstract"`
	Content    string    `json:"content"`
	Tags       []string  `json:"tags"`
	IsArchived bool      `json:"is_archived"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, updatePost,
		arg.ID,
		arg.SemanticID,
		arg.AuthorID,
		arg.Title,
		arg.Abstract,
		arg.Content,
		pq.Array(arg.Tags),
		arg.IsArchived,
		arg.UpdatedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.SemanticID,
		&i.AuthorID,
		&i.Title,
		&i.Abstract,
		&i.Content,
		pq.Array(&i.Tags),
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
